export enum GamificationEventType {
  PROFILE_UPDATED = 'profile_updated',
  JOB_VIEWED = 'job_viewed',
  JOB_SAVED = 'job_saved',
  INTERVIEW_SAVED = 'interview_saved',
  JOB_APPLICATION_SUBMITTED = 'job_application_submitted',
  APPLICATION_STATUS_SHORTLISTED = 'application_status_shortlisted',
  APPLICATION_STATUS_INTERVIEW_SCHEDULED = 'application_status_interview_scheduled',
  APPLICATION_STATUS_ACCEPTED = 'application_status_accepted',
  APPLICATION_STATUS_REJECTED = 'application_status_rejected',
  MOCK_INTERVIEW_STARTED = 'mock_interview_started',
  MOCK_INTERVIEW_COMPLETED = 'mock_interview_completed',
  MOCK_INTERVIEW_SCORE_AWARDED = 'mock_interview_score_awarded',
  RESUME_BUILDER_CREATED = 'resume_builder_created',
  RESUME_BUILDER_SAVED = 'resume_builder_saved',
  ATS_SCAN_COMPLETED = 'ats_scan_completed',
  ATS_SCORE_AWARDED = 'ats_score_awarded',
}
