export const ROUTES = {
  AUTH: {
    BASE: 'auth',
    LOGIN: 'login',
    SIGNUP: 'signup',
    ME: 'me',
    UPDATE_ME: 'update-me',
    OAUTH_LINKED_ACCOUNTS: 'oauth/accounts',
    OAUTH_UNLINK: 'oauth/:provider/unlink',
    PASSWORD_RESET_REQUEST: 'password-reset/request',
    PASSWORD_RESET_VERIFY: 'password-reset/verify',
    PASSWORD_RESET_CONFIRM: 'password-reset/confirm',
    OAUTH_AUTHORIZE: 'oauth/:provider/authorize',
    OAUTH_LINK_AUTHORIZE: 'oauth/:provider/link/authorize',
    OAUTH_CALLBACK: 'oauth/:provider/callback',
    OAUTH_EXCHANGE: 'oauth/exchange',
    OAUTH_LINK_COMPLETE: 'oauth/link/complete',
  },
  ADMIN: {
    BASE: 'admin',
  },
  USER: {
    BASE: 'users',
    BY_ID: ':id',
  },
  COMPANY: {
    BASE: 'companies',
    BY_ID: ':id',
    ME: 'me',
    WORKSPACES_ME: 'workspaces/me',
    JOIN_BY_CODE: 'join-by-code',
    INVITE_CODE_RESET: ':id/invite-code/reset',
    INVITES: ':id/invites',
    RECRUITERS: ':id/recruiters',
    RECRUITER_BY_ID: ':id/recruiters/:recruiterId',
  },
  COLLEGE: {
    BASE: 'colleges',
    BY_ID: ':id',
    ME: 'me',
    WORKSPACES_ME: 'workspaces/me',
    JOIN_BY_CODE: 'join-by-code',
    INVITE_CODE_RESET: ':id/invite-code/reset',
    INVITES: ':id/invites',
    STUDENTS: ':id/students',
    STUDENT_BY_ID: ':id/students/:studentId',
    METRICS: ':id/metrics',
  },
  JOB: {
    BASE: 'jobs',
    BY_ID: ':id',
    METRICS: ':id/metrics',
    VIEW: ':id/view',
  },
  APPLICATION: {
    BASE: 'applications',
    JOB_APPLICATIONS: 'jobs/:jobId',
    MY_APPLICATIONS: 'me',
    MY_APPLICATION_BY_JOB: 'job/:jobId/me',
    RESUMES_ME: 'resumes/me',
    RESUME_BY_ID: 'resumes/:resumeId',
    APPLICATION_BY_JOB: 'jobs/:jobId/:applicationId',
    APPLICATION_RESUME_ACTIVITY:
      'jobs/:jobId/:applicationId/resume-activity',
  },
  LEADERBOARD: {
    BASE: 'leaderboard',
  },
  INTERVIEW: {
    BASE: 'interviews',
    BY_ID: ':id',
    VAPI_VOICE_CREATE_CONFIG: 'vapi/creation-config',
    VAPI_GENERATE: 'vapi/generate',
    SESSIONS: ':id/sessions',
    SESSION_COMPLETE: ':id/sessions/:sessionId/complete',
    MY_SESSIONS: ':id/sessions/me',
    SESSION_FEEDBACK: 'sessions/:sessionId/feedback',
    ANALYTICS: ':id/analytics',
  },
  BOOKMARK: {
    BASE: 'bookmarks',
    ME: 'me',
    JOB: 'jobs/:jobId',
    INTERVIEW: 'interviews/:interviewId',
  },
  RESUME_BUILDER: {
    BASE: 'resume-builder',
    BY_ID: ':id',
    LIST: 'list',
    GENERATE_PDF: ':id/generate-pdf',
    SAVE: ':id/save',
    AI_SUMMARY: 'ai/summary',
    AI_EXPERIENCE_BULLETS: 'ai/experience-bullets',
    AI_SUGGESTIONS: 'ai/suggestions',
    ATS_SCAN: 'ats-scan',
  },
} as const;
